# Generated by Django 3.2 on 2022-11-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpis_backend', '0002_alter_maoni_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maoni',
            name='category',
            field=models.CharField(choices=[('sifa', 'sifa'), ('kosolewa', 'sifa'), ('pendekezo', 'pendekezo')], default='empty', max_length=20),
        ),
    ]
