# Generated by Django 3.2 on 2022-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpis_backend', '0002_rc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekta',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sekta',
            name='jina',
            field=models.CharField(max_length=30),
        ),
    ]
