# Generated by Django 3.2 on 2022-11-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpis_backend', '0003_alter_maoni_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maoni',
            name='category',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='empty', max_length=20),
        ),
    ]
